export interface IEmployeeTask {
  taskId: number;
  employeeName: string;
  department: "Engineering" | "Design" | "QA" | string;
  taskName: string;
  priority: "High" | "Medium" | "Low";
  status: "In Progress" | "Completed" | "At Risk" | "Delayed";
  taskStartDate: Date;
  taskEndDate: Date;
  completionPercentage: number; // 0–100
  performanceScore: number;     // e.g. 1–5 scale
  hoursWorked: number;
  estimatedHours: number;
}

export const employeeTasks: IEmployeeTask[] = [
  {
    taskId: 5001,
    employeeName: "David Miller",
    department: "Engineering",
    taskName: "Cloud Deployment",
    priority: "High",
    status: "In Progress",
    taskStartDate: new Date(2026, 0, 1),
    taskEndDate: new Date(2026, 1, 16),
    completionPercentage: 40,
    performanceScore: 3.0,
    hoursWorked: 24,
    estimatedHours: 60
  },
  {
    taskId: 5002,
    employeeName: "Sophia Johnson",
    department: "Design",
    taskName: "API Integration",
    priority: "Medium",
    status: "Completed",
    taskStartDate: new Date(2026, 1, 2),
    taskEndDate: new Date(2026, 2, 17),
    completionPercentage: 50,
    performanceScore: 3.4,
    hoursWorked: 35,
    estimatedHours: 70
  },
  {
    taskId: 5003,
    employeeName: "Michael Brown",
    department: "QA",
    taskName: "UI Revamp",
    priority: "Low",
    status: "At Risk",
    taskStartDate: new Date(2026, 2, 3),
    taskEndDate: new Date(2026, 3, 18),
    completionPercentage: 60,
    performanceScore: 3.8,
    hoursWorked: 48,
    estimatedHours: 80
  },
  {
    taskId: 5004,
    employeeName: "Emma Davis",
    department: "Engineering",
    taskName: "Performance Optimization",
    priority: "High",
    status: "Delayed",
    taskStartDate: new Date(2026, 3, 4),
    taskEndDate: new Date(2026, 4, 19),
    completionPercentage: 70,
    performanceScore: 4.2,
    hoursWorked: 63,
    estimatedHours: 90
  },
  {
    taskId: 5005,
    employeeName: "Daniel Wilson",
    department: "Design",
    taskName: "Automation Setup",
    priority: "Medium",
    status: "In Progress",
    taskStartDate: new Date(2026, 4, 5),
    taskEndDate: new Date(2026, 5, 20),
    completionPercentage: 80,
    performanceScore: 4.6,
    hoursWorked: 80,
    estimatedHours: 100
  },
  {
    taskId: 5006,
    employeeName: "Olivia Martinez",
    department: "QA",
    taskName: "Regression Testing",
    priority: "Low",
    status: "Completed",
    taskStartDate: new Date(2026, 5, 6),
    taskEndDate: new Date(2026, 6, 21),
    completionPercentage: 90,
    performanceScore: 3.0,
    hoursWorked: 54,
    estimatedHours: 60
  },
  {
    taskId: 5007,
    employeeName: "James Anderson",
    department: "Engineering",
    taskName: "Deployment Automation",
    priority: "High",
    status: "At Risk",
    taskStartDate: new Date(2026, 0, 7),
    taskEndDate: new Date(2026, 1, 22),
    completionPercentage: 40,
    performanceScore: 3.4,
    hoursWorked: 28,
    estimatedHours: 70
  },
  {
    taskId: 5008,
    employeeName: "Isabella Thomas",
    department: "Design",
    taskName: "Service Refactoring",
    priority: "Medium",
    status: "Delayed",
    taskStartDate: new Date(2026, 1, 8),
    taskEndDate: new Date(2026, 2, 23),
    completionPercentage: 50,
    performanceScore: 3.8,
    hoursWorked: 40,
    estimatedHours: 80
  },
  {
    taskId: 5009,
    employeeName: "William Taylor",
    department: "QA",
    taskName: "Security Patch",
    priority: "Low",
    status: "In Progress",
    taskStartDate: new Date(2026, 2, 9),
    taskEndDate: new Date(2026, 3, 24),
    completionPercentage: 60,
    performanceScore: 4.2,
    hoursWorked: 54,
    estimatedHours: 90
  },
  {
    taskId: 5010,
    employeeName: "Ava Hernandez",
    department: "Engineering",
    taskName: "Monitoring Setup",
    priority: "High",
    status: "Completed",
    taskStartDate: new Date(2026, 3, 10),
    taskEndDate: new Date(2026, 4, 25),
    completionPercentage: 70,
    performanceScore: 4.6,
    hoursWorked: 70,
    estimatedHours: 100
  },
  {
    taskId: 5011,
    employeeName: "Ethan Moore",
    department: "Design",
    taskName: "Cloud Deployment",
    priority: "Medium",
    status: "At Risk",
    taskStartDate: new Date(2026, 4, 11),
    taskEndDate: new Date(2026, 5, 26),
    completionPercentage: 80,
    performanceScore: 3.0,
    hoursWorked: 48,
    estimatedHours: 60
  },
  {
    taskId: 5012,
    employeeName: "Mia Clark",
    department: "QA",
    taskName: "API Integration",
    priority: "Low",
    status: "Delayed",
    taskStartDate: new Date(2026, 5, 12),
    taskEndDate: new Date(2026, 6, 27),
    completionPercentage: 90,
    performanceScore: 3.4,
    hoursWorked: 63,
    estimatedHours: 70
  },
  {
    taskId: 5013,
    employeeName: "Lucas Lewis",
    department: "Engineering",
    taskName: "UI Revamp",
    priority: "High",
    status: "In Progress",
    taskStartDate: new Date(2026, 0, 13),
    taskEndDate: new Date(2026, 1, 28),
    completionPercentage: 40,
    performanceScore: 3.8,
    hoursWorked: 32,
    estimatedHours: 80
  },
  {
    taskId: 5014,
    employeeName: "Charlotte Walker",
    department: "Design",
    taskName: "Performance Optimization",
    priority: "Medium",
    status: "Completed",
    taskStartDate: new Date(2026, 1, 14),
    taskEndDate: new Date(2026, 2, 28),
    completionPercentage: 50,
    performanceScore: 4.2,
    hoursWorked: 45,
    estimatedHours: 90
  },
  {
    taskId: 5015,
    employeeName: "Benjamin Hall",
    department: "QA",
    taskName: "Automation Setup",
    priority: "Low",
    status: "At Risk",
    taskStartDate: new Date(2026, 2, 15),
    taskEndDate: new Date(2026, 3, 28),
    completionPercentage: 60,
    performanceScore: 4.6,
    hoursWorked: 60,
    estimatedHours: 100
  },
  {
    taskId: 5016,
    employeeName: "Amelia Allen",
    department: "Engineering",
    taskName: "Regression Testing",
    priority: "High",
    status: "Delayed",
    taskStartDate: new Date(2026, 3, 16),
    taskEndDate: new Date(2026, 4, 28),
    completionPercentage: 70,
    performanceScore: 3.0,
    hoursWorked: 42,
    estimatedHours: 60
  },
  {
    taskId: 5017,
    employeeName: "Henry Young",
    department: "Design",
    taskName: "Deployment Automation",
    priority: "Medium",
    status: "In Progress",
    taskStartDate: new Date(2026, 4, 17),
    taskEndDate: new Date(2026, 5, 28),
    completionPercentage: 80,
    performanceScore: 3.4,
    hoursWorked: 56,
    estimatedHours: 70
  },
  {
    taskId: 5018,
    employeeName: "Harper King",
    department: "QA",
    taskName: "Service Refactoring",
    priority: "Low",
    status: "Completed",
    taskStartDate: new Date(2026, 5, 18),
    taskEndDate: new Date(2026, 6, 28),
    completionPercentage: 90,
    performanceScore: 3.8,
    hoursWorked: 72,
    estimatedHours: 80
  },
  {
    taskId: 5019,
    employeeName: "Alexander Wright",
    department: "Engineering",
    taskName: "Security Patch",
    priority: "High",
    status: "At Risk",
    taskStartDate: new Date(2026, 0, 19),
    taskEndDate: new Date(2026, 1, 28),
    completionPercentage: 40,
    performanceScore: 4.2,
    hoursWorked: 36,
    estimatedHours: 90
  },
  {
    taskId: 5020,
    employeeName: "Evelyn Scott",
    department: "Design",
    taskName: "Monitoring Setup",
    priority: "Medium",
    status: "Delayed",
    taskStartDate: new Date(2026, 1, 20),
    taskEndDate: new Date(2026, 2, 28),
    completionPercentage: 50,
    performanceScore: 4.6,
    hoursWorked: 50,
    estimatedHours: 100
  },
  {
    taskId: 5021,
    employeeName: "David Miller",
    department: "QA",
    taskName: "Cloud Deployment",
    priority: "Low",
    status: "In Progress",
    taskStartDate: new Date(2026, 2, 1),
    taskEndDate: new Date(2026, 3, 16),
    completionPercentage: 60,
    performanceScore: 3.0,
    hoursWorked: 36,
    estimatedHours: 60
  },
  {
    taskId: 5022,
    employeeName: "Sophia Johnson",
    department: "Engineering",
    taskName: "API Integration",
    priority: "High",
    status: "Completed",
    taskStartDate: new Date(2026, 3, 2),
    taskEndDate: new Date(2026, 4, 17),
    completionPercentage: 70,
    performanceScore: 3.4,
    hoursWorked: 49,
    estimatedHours: 70
  },
  {
    taskId: 5023,
    employeeName: "Michael Brown",
    department: "Design",
    taskName: "UI Revamp",
    priority: "Medium",
    status: "At Risk",
    taskStartDate: new Date(2026, 4, 3),
    taskEndDate: new Date(2026, 5, 18),
    completionPercentage: 80,
    performanceScore: 3.8,
    hoursWorked: 64,
    estimatedHours: 80
  },
  {
    taskId: 5024,
    employeeName: "Emma Davis",
    department: "QA",
    taskName: "Performance Optimization",
    priority: "Low",
    status: "Delayed",
    taskStartDate: new Date(2026, 5, 4),
    taskEndDate: new Date(2026, 6, 19),
    completionPercentage: 90,
    performanceScore: 4.2,
    hoursWorked: 81,
    estimatedHours: 90
  },
  {
    taskId: 5025,
    employeeName: "Daniel Wilson",
    department: "Engineering",
    taskName: "Automation Setup",
    priority: "High",
    status: "In Progress",
    taskStartDate: new Date(2026, 0, 5),
    taskEndDate: new Date(2026, 1, 20),
    completionPercentage: 40,
    performanceScore: 4.6,
    hoursWorked: 40,
    estimatedHours: 100
  },
  {
    taskId: 5026,
    employeeName: "Olivia Martinez",
    department: "Design",
    taskName: "Regression Testing",
    priority: "Medium",
    status: "Completed",
    taskStartDate: new Date(2026, 1, 6),
    taskEndDate: new Date(2026, 2, 21),
    completionPercentage: 50,
    performanceScore: 3.0,
    hoursWorked: 30,
    estimatedHours: 60
  },
  {
    taskId: 5027,
    employeeName: "James Anderson",
    department: "QA",
    taskName: "Deployment Automation",
    priority: "Low",
    status: "At Risk",
    taskStartDate: new Date(2026, 2, 7),
    taskEndDate: new Date(2026, 3, 22),
    completionPercentage: 60,
    performanceScore: 3.4,
    hoursWorked: 42,
    estimatedHours: 70
  },
  {
    taskId: 5028,
    employeeName: "Isabella Thomas",
    department: "Engineering",
    taskName: "Service Refactoring",
    priority: "High",
    status: "Delayed",
    taskStartDate: new Date(2026, 3, 8),
    taskEndDate: new Date(2026, 4, 23),
    completionPercentage: 70,
    performanceScore: 3.8,
    hoursWorked: 56,
    estimatedHours: 80
  },
  {
    taskId: 5029,
    employeeName: "William Taylor",
    department: "Design",
    taskName: "Security Patch",
    priority: "Medium",
    status: "In Progress",
    taskStartDate: new Date(2026, 4, 9),
    taskEndDate: new Date(2026, 5, 24),
    completionPercentage: 80,
    performanceScore: 4.2,
    hoursWorked: 72,
    estimatedHours: 90
  },
  {
    taskId: 5030,
    employeeName: "Ava Hernandez",
    department: "QA",
    taskName: "Monitoring Setup",
    priority: "Low",
    status: "Completed",
    taskStartDate: new Date(2026, 5, 10),
    taskEndDate: new Date(2026, 6, 25),
    completionPercentage: 90,
    performanceScore: 4.6,
    hoursWorked: 90,
    estimatedHours: 100
  },
  {
    taskId: 5031,
    employeeName: "Ethan Moore",
    department: "Engineering",
    taskName: "Cloud Deployment",
    priority: "High",
    status: "At Risk",
    taskStartDate: new Date(2026, 0, 11),
    taskEndDate: new Date(2026, 1, 26),
    completionPercentage: 40,
    performanceScore: 3.0,
    hoursWorked: 24,
    estimatedHours: 60
  },
  {
    taskId: 5032,
    employeeName: "Mia Clark",
    department: "Design",
    taskName: "API Integration",
    priority: "Medium",
    status: "Delayed",
    taskStartDate: new Date(2026, 1, 12),
    taskEndDate: new Date(2026, 2, 27),
    completionPercentage: 50,
    performanceScore: 3.4,
    hoursWorked: 35,
    estimatedHours: 70
  },
  {
    taskId: 5033,
    employeeName: "Lucas Lewis",
    department: "QA",
    taskName: "UI Revamp",
    priority: "Low",
    status: "In Progress",
    taskStartDate: new Date(2026, 2, 13),
    taskEndDate: new Date(2026, 3, 28),
    completionPercentage: 60,
    performanceScore: 3.8,
    hoursWorked: 48,
    estimatedHours: 80
  },
  {
    taskId: 5034,
    employeeName: "Charlotte Walker",
    department: "Engineering",
    taskName: "Performance Optimization",
    priority: "High",
    status: "Completed",
    taskStartDate: new Date(2026, 3, 14),
    taskEndDate: new Date(2026, 4, 28),
    completionPercentage: 70,
    performanceScore: 4.2,
    hoursWorked: 63,
    estimatedHours: 90
  },
  {
    taskId: 5035,
    employeeName: "Benjamin Hall",
    department: "Design",
    taskName: "Automation Setup",
    priority: "Medium",
    status: "At Risk",
    taskStartDate: new Date(2026, 4, 15),
    taskEndDate: new Date(2026, 5, 28),
    completionPercentage: 80,
    performanceScore: 4.6,
    hoursWorked: 80,
    estimatedHours: 100
  },
  {
    taskId: 5036,
    employeeName: "Amelia Allen",
    department: "QA",
    taskName: "Regression Testing",
    priority: "Low",
    status: "Delayed",
    taskStartDate: new Date(2026, 5, 16),
    taskEndDate: new Date(2026, 6, 28),
    completionPercentage: 90,
    performanceScore: 3.0,
    hoursWorked: 54,
    estimatedHours: 60
  },
  {
    taskId: 5037,
    employeeName: "Henry Young",
    department: "Engineering",
    taskName: "Deployment Automation",
    priority: "High",
    status: "In Progress",
    taskStartDate: new Date(2026, 0, 17),
    taskEndDate: new Date(2026, 1, 28),
    completionPercentage: 40,
    performanceScore: 3.4,
    hoursWorked: 28,
    estimatedHours: 70
  },
  {
    taskId: 5038,
    employeeName: "Harper King",
    department: "Design",
    taskName: "Service Refactoring",
    priority: "Medium",
    status: "Completed",
    taskStartDate: new Date(2026, 1, 18),
    taskEndDate: new Date(2026, 2, 28),
    completionPercentage: 50,
    performanceScore: 3.8,
    hoursWorked: 40,
    estimatedHours: 80
  },
  {
    taskId: 5039,
    employeeName: "Alexander Wright",
    department: "QA",
    taskName: "Security Patch",
    priority: "Low",
    status: "At Risk",
    taskStartDate: new Date(2026, 2, 19),
    taskEndDate: new Date(2026, 3, 28),
    completionPercentage: 60,
    performanceScore: 4.2,
    hoursWorked: 54,
    estimatedHours: 90
  },
  {
    taskId: 5040,
    employeeName: "Evelyn Scott",
    department: "Engineering",
    taskName: "Monitoring Setup",
    priority: "High",
    status: "Delayed",
    taskStartDate: new Date(2026, 3, 20),
    taskEndDate: new Date(2026, 4, 28),
    completionPercentage: 70,
    performanceScore: 4.6,
    hoursWorked: 70,
    estimatedHours: 100
  },
  {
    taskId: 5041,
    employeeName: "David Miller",
    department: "Design",
    taskName: "Cloud Deployment",
    priority: "Medium",
    status: "In Progress",
    taskStartDate: new Date(2026, 4, 1),
    taskEndDate: new Date(2026, 5, 16),
    completionPercentage: 80,
    performanceScore: 3.0,
    hoursWorked: 48,
    estimatedHours: 60
  },
  {
    taskId: 5042,
    employeeName: "Sophia Johnson",
    department: "QA",
    taskName: "API Integration",
    priority: "Low",
    status: "Completed",
    taskStartDate: new Date(2026, 5, 2),
    taskEndDate: new Date(2026, 6, 17),
    completionPercentage: 90,
    performanceScore: 3.4,
    hoursWorked: 63,
    estimatedHours: 70
  },
  {
    taskId: 5043,
    employeeName: "Michael Brown",
    department: "Engineering",
    taskName: "UI Revamp",
    priority: "High",
    status: "At Risk",
    taskStartDate: new Date(2026, 0, 3),
    taskEndDate: new Date(2026, 1, 18),
    completionPercentage: 40,
    performanceScore: 3.8,
    hoursWorked: 32,
    estimatedHours: 80
  },
  {
    taskId: 5044,
    employeeName: "Emma Davis",
    department: "Design",
    taskName: "Performance Optimization",
    priority: "Medium",
    status: "Delayed",
    taskStartDate: new Date(2026, 1, 4),
    taskEndDate: new Date(2026, 2, 19),
    completionPercentage: 50,
    performanceScore: 4.2,
    hoursWorked: 45,
    estimatedHours: 90
  },
  {
    taskId: 5045,
    employeeName: "Daniel Wilson",
    department: "QA",
    taskName: "Automation Setup",
    priority: "Low",
    status: "In Progress",
    taskStartDate: new Date(2026, 2, 5),
    taskEndDate: new Date(2026, 3, 20),
    completionPercentage: 60,
    performanceScore: 4.6,
    hoursWorked: 60,
    estimatedHours: 100
  },
  {
    taskId: 5046,
    employeeName: "Olivia Martinez",
    department: "Engineering",
    taskName: "Regression Testing",
    priority: "High",
    status: "Completed",
    taskStartDate: new Date(2026, 3, 6),
    taskEndDate: new Date(2026, 4, 21),
    completionPercentage: 70,
    performanceScore: 3.0,
    hoursWorked: 42,
    estimatedHours: 60
  },
  {
    taskId: 5047,
    employeeName: "James Anderson",
    department: "Design",
    taskName: "Deployment Automation",
    priority: "Medium",
    status: "At Risk",
    taskStartDate: new Date(2026, 4, 7),
    taskEndDate: new Date(2026, 5, 22),
    completionPercentage: 80,
    performanceScore: 3.4,
    hoursWorked: 56,
    estimatedHours: 70
  },
  {
    taskId: 5048,
    employeeName: "Isabella Thomas",
    department: "QA",
    taskName: "Service Refactoring",
    priority: "Low",
    status: "Delayed",
    taskStartDate: new Date(2026, 5, 8),
    taskEndDate: new Date(2026, 6, 23),
    completionPercentage: 90,
    performanceScore: 3.8,
    hoursWorked: 72,
    estimatedHours: 80
  },
  {
    taskId: 5049,
    employeeName: "William Taylor",
    department: "Engineering",
    taskName: "Security Patch",
    priority: "High",
    status: "In Progress",
    taskStartDate: new Date(2026, 0, 9),
    taskEndDate: new Date(2026, 1, 24),
    completionPercentage: 40,
    performanceScore: 4.2,
    hoursWorked: 36,
    estimatedHours: 90
  },
  {
    taskId: 5050,
    employeeName: "Ava Hernandez",
    department: "Design",
    taskName: "Monitoring Setup",
    priority: "Medium",
    status: "Completed",
    taskStartDate: new Date(2026, 1, 10),
    taskEndDate: new Date(2026, 2, 25),
    completionPercentage: 50,
    performanceScore: 4.6,
    hoursWorked: 50,
    estimatedHours: 100
  },
  {
    taskId: 5051,
    employeeName: "Ethan Moore",
    department: "QA",
    taskName: "Cloud Deployment",
    priority: "Low",
    status: "At Risk",
    taskStartDate: new Date(2026, 2, 11),
    taskEndDate: new Date(2026, 3, 26),
    completionPercentage: 60,
    performanceScore: 3.0,
    hoursWorked: 36,
    estimatedHours: 60
  },
  {
    taskId: 5052,
    employeeName: "Mia Clark",
    department: "Engineering",
    taskName: "API Integration",
    priority: "High",
    status: "Delayed",
    taskStartDate: new Date(2026, 3, 12),
    taskEndDate: new Date(2026, 4, 27),
    completionPercentage: 70,
    performanceScore: 3.4,
    hoursWorked: 49,
    estimatedHours: 70
  },
  {
    taskId: 5053,
    employeeName: "Lucas Lewis",
    department: "Design",
    taskName: "UI Revamp",
    priority: "Medium",
    status: "In Progress",
    taskStartDate: new Date(2026, 4, 13),
    taskEndDate: new Date(2026, 5, 28),
    completionPercentage: 80,
    performanceScore: 3.8,
    hoursWorked: 64,
    estimatedHours: 80
  },
  {
    taskId: 5054,
    employeeName: "Charlotte Walker",
    department: "QA",
    taskName: "Performance Optimization",
    priority: "Low",
    status: "Completed",
    taskStartDate: new Date(2026, 5, 14),
    taskEndDate: new Date(2026, 6, 28),
    completionPercentage: 90,
    performanceScore: 4.2,
    hoursWorked: 81,
    estimatedHours: 90
  },
  {
    taskId: 5055,
    employeeName: "Benjamin Hall",
    department: "Engineering",
    taskName: "Automation Setup",
    priority: "High",
    status: "At Risk",
    taskStartDate: new Date(2026, 0, 15),
    taskEndDate: new Date(2026, 1, 28),
    completionPercentage: 40,
    performanceScore: 4.6,
    hoursWorked: 40,
    estimatedHours: 100
  },
  {
    taskId: 5056,
    employeeName: "Amelia Allen",
    department: "Design",
    taskName: "Regression Testing",
    priority: "Medium",
    status: "Delayed",
    taskStartDate: new Date(2026, 1, 16),
    taskEndDate: new Date(2026, 2, 28),
    completionPercentage: 50,
    performanceScore: 3.0,
    hoursWorked: 30,
    estimatedHours: 60
  },
  {
    taskId: 5057,
    employeeName: "Henry Young",
    department: "QA",
    taskName: "Deployment Automation",
    priority: "Low",
    status: "In Progress",
    taskStartDate: new Date(2026, 2, 17),
    taskEndDate: new Date(2026, 3, 28),
    completionPercentage: 60,
    performanceScore: 3.4,
    hoursWorked: 42,
    estimatedHours: 70
  },
  {
    taskId: 5058,
    employeeName: "Harper King",
    department: "Engineering",
    taskName: "Service Refactoring",
    priority: "High",
    status: "Completed",
    taskStartDate: new Date(2026, 3, 18),
    taskEndDate: new Date(2026, 4, 28),
    completionPercentage: 70,
    performanceScore: 3.8,
    hoursWorked: 56,
    estimatedHours: 80
  },
  {
    taskId: 5059,
    employeeName: "Alexander Wright",
    department: "Design",
    taskName: "Security Patch",
    priority: "Medium",
    status: "At Risk",
    taskStartDate: new Date(2026, 4, 19),
    taskEndDate: new Date(2026, 5, 28),
    completionPercentage: 80,
    performanceScore: 4.2,
    hoursWorked: 72,
    estimatedHours: 90
  },
  {
    taskId: 5060,
    employeeName: "Evelyn Scott",
    department: "QA",
    taskName: "Monitoring Setup",
    priority: "Low",
    status: "Delayed",
    taskStartDate: new Date(2026, 5, 20),
    taskEndDate: new Date(2026, 6, 28),
    completionPercentage: 90,
    performanceScore: 4.6,
    hoursWorked: 90,
    estimatedHours: 100
  },
  {
    taskId: 5061,
    employeeName: "David Miller",
    department: "Engineering",
    taskName: "Cloud Deployment",
    priority: "High",
    status: "In Progress",
    taskStartDate: new Date(2026, 0, 1),
    taskEndDate: new Date(2026, 1, 16),
    completionPercentage: 40,
    performanceScore: 3.0,
    hoursWorked: 24,
    estimatedHours: 60
  },
  {
    taskId: 5062,
    employeeName: "Sophia Johnson",
    department: "Design",
    taskName: "API Integration",
    priority: "Medium",
    status: "Completed",
    taskStartDate: new Date(2026, 1, 2),
    taskEndDate: new Date(2026, 2, 17),
    completionPercentage: 50,
    performanceScore: 3.4,
    hoursWorked: 35,
    estimatedHours: 70
  },
  {
    taskId: 5063,
    employeeName: "Michael Brown",
    department: "QA",
    taskName: "UI Revamp",
    priority: "Low",
    status: "At Risk",
    taskStartDate: new Date(2026, 2, 3),
    taskEndDate: new Date(2026, 3, 18),
    completionPercentage: 60,
    performanceScore: 3.8,
    hoursWorked: 48,
    estimatedHours: 80
  },
  {
    taskId: 5064,
    employeeName: "Emma Davis",
    department: "Engineering",
    taskName: "Performance Optimization",
    priority: "High",
    status: "Delayed",
    taskStartDate: new Date(2026, 3, 4),
    taskEndDate: new Date(2026, 4, 19),
    completionPercentage: 70,
    performanceScore: 4.2,
    hoursWorked: 63,
    estimatedHours: 90
  },
  {
    taskId: 5065,
    employeeName: "Daniel Wilson",
    department: "Design",
    taskName: "Automation Setup",
    priority: "Medium",
    status: "In Progress",
    taskStartDate: new Date(2026, 4, 5),
    taskEndDate: new Date(2026, 5, 20),
    completionPercentage: 80,
    performanceScore: 4.6,
    hoursWorked: 80,
    estimatedHours: 100
  },
  {
    taskId: 5066,
    employeeName: "Olivia Martinez",
    department: "QA",
    taskName: "Regression Testing",
    priority: "Low",
    status: "Completed",
    taskStartDate: new Date(2026, 5, 6),
    taskEndDate: new Date(2026, 6, 21),
    completionPercentage: 90,
    performanceScore: 3.0,
    hoursWorked: 54,
    estimatedHours: 60
  },
  {
    taskId: 5067,
    employeeName: "James Anderson",
    department: "Engineering",
    taskName: "Deployment Automation",
    priority: "High",
    status: "At Risk",
    taskStartDate: new Date(2026, 0, 7),
    taskEndDate: new Date(2026, 1, 22),
    completionPercentage: 40,
    performanceScore: 3.4,
    hoursWorked: 28,
    estimatedHours: 70
  },
  {
    taskId: 5068,
    employeeName: "Isabella Thomas",
    department: "Design",
    taskName: "Service Refactoring",
    priority: "Medium",
    status: "Delayed",
    taskStartDate: new Date(2026, 1, 8),
    taskEndDate: new Date(2026, 2, 23),
    completionPercentage: 50,
    performanceScore: 3.8,
    hoursWorked: 40,
    estimatedHours: 80
  },
  {
    taskId: 5069,
    employeeName: "William Taylor",
    department: "QA",
    taskName: "Security Patch",
    priority: "Low",
    status: "In Progress",
    taskStartDate: new Date(2026, 2, 9),
    taskEndDate: new Date(2026, 3, 24),
    completionPercentage: 60,
    performanceScore: 4.2,
    hoursWorked: 54,
    estimatedHours: 90
  },
  {
    taskId: 5070,
    employeeName: "Ava Hernandez",
    department: "Engineering",
    taskName: "Monitoring Setup",
    priority: "High",
    status: "Completed",
    taskStartDate: new Date(2026, 3, 10),
    taskEndDate: new Date(2026, 4, 25),
    completionPercentage: 70,
    performanceScore: 4.6,
    hoursWorked: 70,
    estimatedHours: 100
  },
  {
    taskId: 5071,
    employeeName: "Ethan Moore",
    department: "Design",
    taskName: "Cloud Deployment",
    priority: "Medium",
    status: "At Risk",
    taskStartDate: new Date(2026, 4, 11),
    taskEndDate: new Date(2026, 5, 26),
    completionPercentage: 80,
    performanceScore: 3.0,
    hoursWorked: 48,
    estimatedHours: 60
  },
  {
    taskId: 5072,
    employeeName: "Mia Clark",
    department: "QA",
    taskName: "API Integration",
    priority: "Low",
    status: "Delayed",
    taskStartDate: new Date(2026, 5, 12),
    taskEndDate: new Date(2026, 6, 27),
    completionPercentage: 90,
    performanceScore: 3.4,
    hoursWorked: 63,
    estimatedHours: 70
  },
  {
    taskId: 5073,
    employeeName: "Lucas Lewis",
    department: "Engineering",
    taskName: "UI Revamp",
    priority: "High",
    status: "In Progress",
    taskStartDate: new Date(2026, 0, 13),
    taskEndDate: new Date(2026, 1, 28),
    completionPercentage: 40,
    performanceScore: 3.8,
    hoursWorked: 32,
    estimatedHours: 80
  },
  {
    taskId: 5074,
    employeeName: "Charlotte Walker",
    department: "Design",
    taskName: "Performance Optimization",
    priority: "Medium",
    status: "Completed",
    taskStartDate: new Date(2026, 1, 14),
    taskEndDate: new Date(2026, 2, 28),
    completionPercentage: 50,
    performanceScore: 4.2,
    hoursWorked: 45,
    estimatedHours: 90
  },
  {
    taskId: 5075,
    employeeName: "Benjamin Hall",
    department: "QA",
    taskName: "Automation Setup",
    priority: "Low",
    status: "At Risk",
    taskStartDate: new Date(2026, 2, 15),
    taskEndDate: new Date(2026, 3, 28),
    completionPercentage: 60,
    performanceScore: 4.6,
    hoursWorked: 60,
    estimatedHours: 100
  },
  {
    taskId: 5076,
    employeeName: "Amelia Allen",
    department: "Engineering",
    taskName: "Regression Testing",
    priority: "High",
    status: "Delayed",
    taskStartDate: new Date(2026, 3, 16),
    taskEndDate: new Date(2026, 4, 28),
    completionPercentage: 70,
    performanceScore: 3.0,
    hoursWorked: 42,
    estimatedHours: 60
  },
  {
    taskId: 5077,
    employeeName: "Henry Young",
    department: "Design",
    taskName: "Deployment Automation",
    priority: "Medium",
    status: "In Progress",
    taskStartDate: new Date(2026, 4, 17),
    taskEndDate: new Date(2026, 5, 28),
    completionPercentage: 80,
    performanceScore: 3.4,
    hoursWorked: 56,
    estimatedHours: 70
  },
  {
    taskId: 5078,
    employeeName: "Harper King",
    department: "QA",
    taskName: "Service Refactoring",
    priority: "Low",
    status: "Completed",
    taskStartDate: new Date(2026, 5, 18),
    taskEndDate: new Date(2026, 6, 28),
    completionPercentage: 90,
    performanceScore: 3.8,
    hoursWorked: 72,
    estimatedHours: 80
  },
  {
    taskId: 5079,
    employeeName: "Alexander Wright",
    department: "Engineering",
    taskName: "Security Patch",
    priority: "High",
    status: "At Risk",
    taskStartDate: new Date(2026, 0, 19),
    taskEndDate: new Date(2026, 1, 28),
    completionPercentage: 40,
    performanceScore: 4.2,
    hoursWorked: 36,
    estimatedHours: 90
  },
  {
    taskId: 5080,
    employeeName: "Evelyn Scott",
    department: "Design",
    taskName: "Monitoring Setup",
    priority: "Medium",
    status: "Delayed",
    taskStartDate: new Date(2026, 1, 20),
    taskEndDate: new Date(2026, 2, 28),
    completionPercentage: 50,
    performanceScore: 4.6,
    hoursWorked: 50,
    estimatedHours: 100
  },
  {
    taskId: 5081,
    employeeName: "David Miller",
    department: "QA",
    taskName: "Cloud Deployment",
    priority: "Low",
    status: "In Progress",
    taskStartDate: new Date(2026, 2, 1),
    taskEndDate: new Date(2026, 3, 16),
    completionPercentage: 60,
    performanceScore: 3.0,
    hoursWorked: 36,
    estimatedHours: 60
  },
  {
    taskId: 5082,
    employeeName: "Sophia Johnson",
    department: "Engineering",
    taskName: "API Integration",
    priority: "High",
    status: "Completed",
    taskStartDate: new Date(2026, 3, 2),
    taskEndDate: new Date(2026, 4, 17),
    completionPercentage: 70,
    performanceScore: 3.4,
    hoursWorked: 49,
    estimatedHours: 70
  },
  {
    taskId: 5083,
    employeeName: "Michael Brown",
    department: "Design",
    taskName: "UI Revamp",
    priority: "Medium",
    status: "At Risk",
    taskStartDate: new Date(2026, 4, 3),
    taskEndDate: new Date(2026, 5, 18),
    completionPercentage: 80,
    performanceScore: 3.8,
    hoursWorked: 64,
    estimatedHours: 80
  },
  {
    taskId: 5084,
    employeeName: "Emma Davis",
    department: "QA",
    taskName: "Performance Optimization",
    priority: "Low",
    status: "Delayed",
    taskStartDate: new Date(2026, 5, 4),
    taskEndDate: new Date(2026, 6, 19),
    completionPercentage: 90,
    performanceScore: 4.2,
    hoursWorked: 81,
    estimatedHours: 90
  },
  {
    taskId: 5085,
    employeeName: "Daniel Wilson",
    department: "Engineering",
    taskName: "Automation Setup",
    priority: "High",
    status: "In Progress",
    taskStartDate: new Date(2026, 0, 5),
    taskEndDate: new Date(2026, 1, 20),
    completionPercentage: 40,
    performanceScore: 4.6,
    hoursWorked: 40,
    estimatedHours: 100
  },
  {
    taskId: 5086,
    employeeName: "Olivia Martinez",
    department: "Design",
    taskName: "Regression Testing",
    priority: "Medium",
    status: "Completed",
    taskStartDate: new Date(2026, 1, 6),
    taskEndDate: new Date(2026, 2, 21),
    completionPercentage: 50,
    performanceScore: 3.0,
    hoursWorked: 30,
    estimatedHours: 60
  },
  {
    taskId: 5087,
    employeeName: "James Anderson",
    department: "QA",
    taskName: "Deployment Automation",
    priority: "Low",
    status: "At Risk",
    taskStartDate: new Date(2026, 2, 7),
    taskEndDate: new Date(2026, 3, 22),
    completionPercentage: 60,
    performanceScore: 3.4,
    hoursWorked: 42,
    estimatedHours: 70
  },
  {
    taskId: 5088,
    employeeName: "Isabella Thomas",
    department: "Engineering",
    taskName: "Service Refactoring",
    priority: "High",
    status: "Delayed",
    taskStartDate: new Date(2026, 3, 8),
    taskEndDate: new Date(2026, 4, 23),
    completionPercentage: 70,
    performanceScore: 3.8,
    hoursWorked: 56,
    estimatedHours: 80
  },
  {
    taskId: 5089,
    employeeName: "William Taylor",
    department: "Design",
    taskName: "Security Patch",
    priority: "Medium",
    status: "In Progress",
    taskStartDate: new Date(2026, 4, 9),
    taskEndDate: new Date(2026, 5, 24),
    completionPercentage: 80,
    performanceScore: 4.2,
    hoursWorked: 72,
    estimatedHours: 90
  },
  {
    taskId: 5090,
    employeeName: "Ava Hernandez",
    department: "QA",
    taskName: "Monitoring Setup",
    priority: "Low",
    status: "Completed",
    taskStartDate: new Date(2026, 5, 10),
    taskEndDate: new Date(2026, 6, 25),
    completionPercentage: 90,
    performanceScore: 4.6,
    hoursWorked: 90,
    estimatedHours: 100
  },
  {
    taskId: 5091,
    employeeName: "Ethan Moore",
    department: "Engineering",
    taskName: "Cloud Deployment",
    priority: "High",
    status: "At Risk",
    taskStartDate: new Date(2026, 0, 11),
    taskEndDate: new Date(2026, 1, 26),
    completionPercentage: 40,
    performanceScore: 3.0,
    hoursWorked: 24,
    estimatedHours: 60
  },
  {
    taskId: 5092,
    employeeName: "Mia Clark",
    department: "Design",
    taskName: "API Integration",
    priority: "Medium",
    status: "Delayed",
    taskStartDate: new Date(2026, 1, 12),
    taskEndDate: new Date(2026, 2, 27),
    completionPercentage: 50,
    performanceScore: 3.4,
    hoursWorked: 35,
    estimatedHours: 70
  },
  {
    taskId: 5093,
    employeeName: "Lucas Lewis",
    department: "QA",
    taskName: "UI Revamp",
    priority: "Low",
    status: "In Progress",
    taskStartDate: new Date(2026, 2, 13),
    taskEndDate: new Date(2026, 3, 28),
    completionPercentage: 60,
    performanceScore: 3.8,
    hoursWorked: 48,
    estimatedHours: 80
  },
  {
    taskId: 5094,
    employeeName: "Charlotte Walker",
    department: "Engineering",
    taskName: "Performance Optimization",
    priority: "High",
    status: "Completed",
    taskStartDate: new Date(2026, 3, 14),
    taskEndDate: new Date(2026, 4, 28),
    completionPercentage: 70,
    performanceScore: 4.2,
    hoursWorked: 63,
    estimatedHours: 90
  },
  {
    taskId: 5095,
    employeeName: "Benjamin Hall",
    department: "Design",
    taskName: "Automation Setup",
    priority: "Medium",
    status: "At Risk",
    taskStartDate: new Date(2026, 4, 15),
    taskEndDate: new Date(2026, 5, 28),
    completionPercentage: 80,
    performanceScore: 4.6,
    hoursWorked: 80,
    estimatedHours: 100
  },
  {
    taskId: 5096,
    employeeName: "Amelia Allen",
    department: "QA",
    taskName: "Regression Testing",
    priority: "Low",
    status: "Delayed",
    taskStartDate: new Date(2026, 5, 16),
    taskEndDate: new Date(2026, 6, 28),
    completionPercentage: 90,
    performanceScore: 3.0,
    hoursWorked: 54,
    estimatedHours: 60
  },
  {
    taskId: 5097,
    employeeName: "Henry Young",
    department: "Engineering",
    taskName: "Deployment Automation",
    priority: "High",
    status: "In Progress",
    taskStartDate: new Date(2026, 0, 17),
    taskEndDate: new Date(2026, 1, 28),
    completionPercentage: 40,
    performanceScore: 3.4,
    hoursWorked: 28,
    estimatedHours: 70
  },
  {
    taskId: 5098,
    employeeName: "Harper King",
    department: "Design",
    taskName: "Service Refactoring",
    priority: "Medium",
    status: "Completed",
    taskStartDate: new Date(2026, 1, 18),
    taskEndDate: new Date(2026, 2, 28),
    completionPercentage: 50,
    performanceScore: 3.8,
    hoursWorked: 40,
    estimatedHours: 80
  },
  {
    taskId: 5099,
    employeeName: "Alexander Wright",
    department: "QA",
    taskName: "Security Patch",
    priority: "Low",
    status: "At Risk",
    taskStartDate: new Date(2026, 2, 19),
    taskEndDate: new Date(2026, 3, 28),
    completionPercentage: 60,
    performanceScore: 4.2,
    hoursWorked: 54,
    estimatedHours: 90
  },
  {
    taskId: 5100,
    employeeName: "Evelyn Scott",
    department: "Engineering",
    taskName: "Monitoring Setup",
    priority: "High",
    status: "Delayed",
    taskStartDate: new Date(2026, 3, 20),
    taskEndDate: new Date(2026, 4, 28),
    completionPercentage: 70,
    performanceScore: 4.6,
    hoursWorked: 70,
    estimatedHours: 100
  }
];